# Generated by Django 5.2.7 on 2025-11-05 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_category_name_alter_category_slug_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='postal_code',
            new_name='pincode',
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='products/', upload_to='products/'),
        ),
    ]
