# Generated by Django 5.2.7 on 2025-11-05 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_rename_postal_code_order_pincode_alter_product_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at']},
        ),
    ]
