# Generated by Django 5.2.7 on 2025-11-26 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_order_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[ ('C', 'Completed')], default='C', max_length=1),
        ),
    ]
